const roles = {
    admin: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/team",
      "/dashboard/contacts",
      "/dashboard/invoices",
      "/dashboard/form",
      "/dashboard/calendar",
      "/dashboard/faq",
      "/dashboard/bar",
      "/dashboard/pie",
      "/dashboard/line",
      "/dashboard/geography",
      "/dashboard/stream",
    ],
    ASO: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/team",
      "/dashboard/contacts",
      "/dashboard/invoices",
      "/dashboard/form",
      "/dashboard/calendar",
      "/dashboard/faq",
      "/dashboard/bar",
      "/dashboard/pie",
      "/dashboard/line",
      "/dashboard/geography",
      "/dashboard/stream",
    ],
    SO: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/team",
      "/dashboard/contacts",
      "/dashboard/invoices",
      "/dashboard/form",
      "/dashboard/calendar",
      "/dashboard/faq",
      "/dashboard/bar",
      "/dashboard/pie",
      "/dashboard/line",
      "/dashboard/geography",
      "/dashboard/stream",
    ],
    undersecretary: [
      "/dashboard",
      "/dashboard/admin",
      "/dashboard/team",
      "/dashboard/contacts",
      "/dashboard/invoices",
      "/dashboard/form",
      "/dashboard/calendar",
      "/dashboard/faq",
      "/dashboard/bar",
      "/dashboard/pie",
      "/dashboard/line",
      "/dashboard/geography",
      "/dashboard/stream",
    ],
  };
  
  export default roles;
  